const chatBotMsgList = [
  "Hi", "Hey", "Good Morning", "Good Evening", "How can I help you?", "Thank You",
  "Hello", "Greetings", "Good Afternoon", "Good Night", "What's up?", "You're welcome",
  "How are you?", "Nice to meet you", "Good to see you", "How have you been?", 
  "Long time no see", "How's everything?", "Take care", "Goodbye", "See you later", 
  "Have a nice day", "Happy to help", "Anytime", "Best regards", "Cheers", 
  "Catch you later", "See you soon", "Talk to you later", "Good luck", 
  "Farewell", "Until next time", "Much appreciated", "Glad to assist", "My pleasure",
  "No problem", "Thanks a lot", "Thanks a million", "Thanks so much", 
  "I appreciate it", "It’s my duty", "I’m here for you", "Any other questions?",
  "What can I do for you?", "How may I assist?", "What’s going on?", 
  "What’s new?", "How’s life?", "What’s happening?", "Good to meet you", 
  "Glad to meet you", "How do you do?", "Pleasure meeting you", "Nice seeing you", 
  "How’s it going?", "Good to hear from you", "Welcome back", "How’s your day?",
  "Hope all is well", "Great to see you", "Been a while", "Nice catching up", 
  "Until we meet again", "Safe travels", "Wish you well", "Take it easy", 
  "All the best", "Be well", "See you around", "Stay safe", "Stay in touch", 
  "Let’s catch up", "Keep in touch", "Give my regards", "Looking forward", 
  "Keep me posted", "Keep me updated", "Keep in mind", "Remember me", 
  "Stay connected", "Don’t forget", "Do you need anything?", "Can I assist?", 
  "Anything else?", "Anything more?", "Need more help?", "How can I be of service?",
  "Shall I assist?", "Happy to assist", "Here to help", "I’m available", 
  "Just ask", "Let me know", "I’m all ears", "Glad to help", "I’m at your service",
  "Your wish is my command", "What’s up?", "What can I do?", "At your service",
  "What do you need?", "How can I support?", "How can I serve?", "Need help?",
  "Can I help?", "Is there anything?", "Looking for assistance?", "Can I assist you?",
  "Here if you need me", "I’m ready", "Just tell me", "How can I be useful?",
  "What do you require?", "Anything you need?", "Need a hand?", "Lend you a hand?",
  "Offering my help", "Here to assist", "Here for you", "Ready to help", 
  "Always here", "Anything for you", "Let’s get started", "Let’s begin", 
  "Shall we start?", "Ready when you are", "Let’s do this", "Here we go", 
  "All set?", "Prepared?", "Ready to go?", "Whenever you’re ready", 
  "Shall we proceed?", "Let’s move forward", "Ready and waiting", 
  "Standing by", "At your command", "What’s next?", "Next step?", 
  "Shall we continue?", "Moving on", "How can I assist you today?", 
  "What’s your request?", "Do you need assistance?", "Here for support", 
  "I’m at your service", "How can I make your day?", "Is there something you need?",
  "What can I do for you?", "I’m ready to assist", "Ready to help you", 
  "How can I help you?", "What would you like?", "What can I assist with?", 
  "Need something?", "Assistance needed?", "How can I aid you?", 
  "Looking for help?", "What can I do today?", "Shall I support you?", 
  "What’s your command?", "Command me", "I’m at your disposal", 
  "Here to be of service", "I’m all set", "Let’s make it happen", 
  "What do you want to do?", "Shall we get going?", "Ready to assist you",
  "How can I make it easier?", "Need a hand?", "Looking for assistance?", 
  "I’m all set", "How’s your day going?", "Anything on your mind?", 
  "Ready to support", "I’m here for that", "I’m here for this", 
  "What can I handle for you?", "Here to manage it", "Let’s take care of it", 
  "Let’s get this done", "Ready for action", "How can I help today?", 
  "Anything I can handle?", "I’m up for it", "Here to make it easier", 
  "Just let me know", "I’m here for you", "I’m here to help", 
  "Whatever you need", "I’m here to assist", "Just ask", "Let’s do this", 
  "I’m ready", "Let’s start", "What do you need?", "Anything I can do?", 
  "What’s next?", "What’s on the agenda?", "What’s planned?", 
  "I’m here to help", "Can I assist?", "Here to support", "At your service", 
  "Whatever you need", "Here to serve", "How can I help?", "Ready when you are","Hi", "Hey", "Good Morning", "Good Evening", "How can I help you?", "Thank You",
    "Hello", "Howdy", "What's up?", "Good Night", "You're welcome", "Please", 
    "Excuse me", "Sorry", "No problem", "See you later", "Take care", 
    "Best wishes", "Good luck", "Congratulations", "Happy Birthday", "Merry Christmas",
    "Happy New Year", "Goodbye", "Cheers", "Good afternoon", "Good to see you", 
    "Nice to meet you", "Pleased to meet you", "How are you?", "I'm fine", 
    "How have you been?", "Nice day", "Lovely day", "Happy anniversary", 
    "Welcome", "Greetings", "Have a nice day", "Bon voyage", "Safe travels",
    "Get well soon", "Happy holidays", "All the best", "Take it easy", "Be well",
    "Keep in touch", "Long time no see", "It's been a while", "Let's catch up", 
    "Let's meet up", "Good to hear from you", "It’s a pleasure", "Delighted", 
    "Good job", "Well done", "Excellent", "Great", "Fantastic", "Amazing",
    "Brilliant", "Superb", "Outstanding", "Incredible", "Marvelous", 
    "Terrific", "Fabulous", "Awesome", "Splendid", "Wonderful", 
    "Remarkable", "Impressive", "Spectacular", "Extraordinary", "Perfect", 
    "Top-notch", "Phenomenal", "Exceptional", "Super", "Bravo", "Kudos", 
    "Great work", "Hats off", "Way to go", "Good going", "Nice work", 
    "Good effort", "Nice try", "Keep it up", "Well played", "Nice play", 
    "Nice shot", "You're amazing", "You're the best", "You rock", 
    "You're awesome", "You're incredible", "You did it", "You nailed it", 
    "You're on fire", "You're unstoppable", "You're a star", "You're a champ", 
    "You're fantastic", "You're remarkable", "You're impressive", 
    "You're outstanding", "You're phenomenal", "You're extraordinary", 
    "You're fabulous", "You're marvelous", "You're superb", "You're brilliant", 
    "You're a genius", "You're talented", "You're gifted", "You're skilled", 
    "You're clever", "You're smart", "You're wise", "You're sharp", 
    "You're quick", "You're witty", "You're intelligent", "You're resourceful", 
    "You're capable", "You're competent", "You're efficient", "You're effective", 
    "You're hardworking", "You're diligent", "You're dedicated", 
    "You're committed", "You're reliable", "You're trustworthy", 
    "You're dependable", "You're responsible", "You're responsive", 
    "You're proactive", "You're punctual", "You're organized", "You're tidy", 
    "You're neat", "You're disciplined", "You're focused", "You're determined", 
    "You're persistent", "You're patient", "You're calm", "You're composed", 
    "You're serene", "You're tranquil", "You're peaceful", "You're content", 
    "You're happy", "You're joyful", "You're cheerful", "You're jolly", 
    "You're merry", "You're lively", "You're enthusiastic", "You're energetic", 
    "You're vibrant", "You're dynamic", "You're spirited", "You're passionate", 
    "You're zealous", "You're motivated", "You're driven", "You're ambitious", 
    "You're eager", "You're excited", "You're enthusiastic", "You're optimistic", 
    "You're hopeful", "You're positive", "You're confident", "You're assertive", 
    "You're strong", "You're resilient", "You're tough", "You're brave", 
    "You're courageous", "You're bold", "You're fearless", "You're daring", 
    "You're adventurous", "You're curious", "You're inquisitive", "You're inventive", 
    "You're innovative", "You're creative", "You're imaginative", "You're original", 
    "You're resourceful", "You're versatile", "You're flexible", "You're adaptable", 
    "You're agile", "You're nimble", "You're quick-witted", "You're sharp-minded", 
    "You're clear-headed", "You're focused", "You're alert", "You're attentive", 
    "You're observant", "You're perceptive", "You're insightful", 
    "You're thoughtful", "You're considerate", "You're compassionate", 
    "You're empathetic", "You're kind", "You're generous", "You're giving", 
    "You're caring", "You're loving", "You're affectionate", "You're warm", 
    "You're friendly", "You're sociable", "You're outgoing", "You're gregarious", 
    "You're talkative", "You're articulate", "You're expressive", 
    "You're communicative", "You're understanding", "You're patient", 
    "You're tolerant", "You're forgiving", "You're open-minded", 
    "You're fair-minded", "You're just", "You're impartial", "You're unbiased", 
    "You're objective", "You're neutral", "You're balanced", "You're reasonable", 
    "You're rational", "You're logical", "You're sensible", "You're practical", 
    "You're down-to-earth", "You're realistic", "You're pragmatic", 
    "You're level-headed", "You're calm", "You're composed", "You're serene", 
    "You're peaceful", "You're content", "You're satisfied", "You're fulfilled", 
    "You're happy", "You're joyful", "You're cheerful", "You're jolly", 
    "You're merry", "You're lively", "You're enthusiastic", "You're energetic", 
    "You're vibrant", "You're dynamic", "You're spirited", "You're passionate", 
    "You're zealous", "You're motivated", "You're driven", "You're ambitious", 
    "You're eager", "You're excited", "You're enthusiastic", "You're optimistic", 
    "You're hopeful", "You're positive", "You're confident", "You're assertive", 
    "You're strong", "You're resilient", "You're tough", "You're brave", 
    "You're courageous", "You're bold", "You're fearless", "You're daring", 
    "You're adventurous", "You're curious", "You're inquisitive", "You're inventive", 
    "You're innovative", "You're creative", "You're imaginative", "You're original", 
    "You're resourceful", "You're versatile", "You're flexible", "You're adaptable", 
    "You're agile", "You're nimble", "You're quick-witted", "You're sharp-minded", 
    "You're clear-headed", "You're focused", "You're alert", "You're attentive", 
    "You're observant", "You're perceptive", "You're insightful", 
    "You're thoughtful", "You're considerate", "You're compassionate", 
    "You're empathetic", "You're kind", "You're generous", "You're giving", 
    "You're caring", "You're loving", "You're affectionate", "You're warm", 
    "You're friendly", "You're sociable", "You're outgoing", "You're gregarious", 
    "You're talkative", "You're articulate", "You're expressive", 
    "You're communicative", "You're understanding", "You're patient", 
    "You're tolerant", "You're forgiving", "You're open-minded", 
    "You're fair-minded", "You're just", "You're impartial", "You're unbiased", 
    "You're objective", "You're neutral", "You're balanced", "You're reasonable", 
    "You're rational", "You're logical", "You're sensible", "You're practical", 
    "You're down-to-earth", "You're realistic", "You're pragmatic", 
    "You're level-headed", "You're calm", "You're composed", "You're serene", 
    "You're peaceful", "You're content", "You're satisfied", "You're fulfilled", 
    "You're happy", "You're joyful", "You're cheerful", "You're jolly", 
    "You're merry", "You're lively", "You're enthusiastic", "You're energetic", 
    "You're vibrant", "You're dynamic", "You're spirited", "You're passionate", 
    "You're zealous", "You're motivated", "You're driven", "You're ambitious", 
    "You're eager", "You're excited", "You're enthusiastic", "You're optimistic", 
    "You're hopeful", "You're positive", "You're confident", "You're assertive", 
    "You're strong", "You're resilient", "You're tough", "You're brave", 
    "You're courageous", "You're bold", "You're fearless", "You're daring", 
    "You're adventurous", "You're curious", "You're inquisitive", "You're inventive", 
    "You're innovative", "You're creative", "You're imaginative", "You're original", 
    "You're resourceful", "You're versatile", "You're flexible", "You're adaptable", 
    "You're agile", "You're nimble", "You're quick-witted", "You're sharp-minded", 
    "You're clear-headed", "You're focused", "You're alert", "You're attentive", 
    "You're observant", "You're perceptive", "You're insightful", 
    "You're thoughtful", "You're considerate", "You're compassionate", 
    "You're empathetic", "You're kind", "You're generous", "You're giving", 
    "You're caring", "You're loving", "You're affectionate", "You're warm", 
    "You're friendly", "You're sociable", "You're outgoing", "You're gregarious", 
    "You're talkative", "You're articulate", "You're expressive", 
    "You're communicative", "You're understanding", "You're patient", 
    "You're tolerant", "You're forgiving", "You're open-minded", 
    "You're fair-minded", "You're just", "You're impartial", "You're unbiased", 
    "You're objective", "You're neutral", "You're balanced", "You're reasonable", 
    "You're rational", "You're logical", "You're sensible", "You're practical", 
    "You're down-to-earth", "You're realistic", "You're pragmatic", 
    "You're level-headed", "You're calm", "You're composed", "You're serene", 
    "You're peaceful", "You're content", "You're satisfied", "You're fulfilled", 
    "You're happy", "You're joyful", "You're cheerful", "You're jolly", 
    "You're merry", "You're lively", "You're enthusiastic", "You're energetic", 
    "You're vibrant", "You're dynamic", "You're spirited", "You're passionate", 
    "You're zealous", "You're motivated", "You're driven", "You're ambitious", 
    "You're eager", "You're excited", "You're enthusiastic", "You're optimistic", 
    "You're hopeful", "You're positive", "You're confident", "You're assertive", 
    "You're strong", "You're resilient", "You're tough", "You're brave", 
    "You're courageous", "You're bold", "You're fearless", "You're daring", 
    "You're adventurous", "You're curious", "You're inquisitive", "You're inventive", 
    "You're innovative", "You're creative", "You're imaginative", "You're original", 
    "You're resourceful", "You're versatile", "You're flexible", "You're adaptable", 
    "You're agile", "You're nimble", "You're quick-witted", "You're sharp-minded", 
    "You're clear-headed", "You're focused", "You're alert", "You're attentive", 
    "You're observant", "You're perceptive", "You're insightful", 
    "You're thoughtful", "You're considerate", "You're compassionate", 
    "You're empathetic", "You're kind", "You're generous", "You're giving", 
    "You're caring", "You're loving", "You're affectionate", "You're warm", 
    "You're friendly", "You're sociable", "You're outgoing", "You're gregarious", 
    "You're talkative", "You're articulate", "You're expressive", 
    "You're communicative", "You're understanding", "You're patient", 
    "You're tolerant", "You're forgiving", "You're open-minded", 
    "You're fair-minded", "You're just", "You're impartial", "You're unbiased", 
    "You're objective", "You're neutral", "You're balanced", "You're reasonable", 
    "You're rational", "You're logical", "You're sensible", "You're practical", 
    "You're down-to-earth", "You're realistic", "You're pragmatic", 
    "You're level-headed", "You're calm", "You're composed", "You're serene", 
    "You're peaceful", "You're content", "You're satisfied", "You're fulfilled", 
    "You're happy", "You're joyful", "You're cheerful", "You're jolly", 
    "You're merry", "You're lively", "You're enthusiastic", "You're energetic", 
    "You're vibrant", "You're dynamic", "You're spirited", "You're passionate", 
    "You're zealous", "You're motivated", "You're driven", "You're ambitious", 
    "You're eager", "You're excited", "You're enthusiastic", "You're optimistic", 
    "You're hopeful", "You're positive", "You're confident", "You're assertive", 
    "You're strong", "You're resilient", "You're tough", "You're brave", 
    "You're courageous", "You're bold", "You're fearless", "You're daring", 
    "You're adventurous", "You're curious", "You're inquisitive", "You're inventive", 
    "You're innovative", "You're creative", "You're imaginative", "You're original", 
    "You're resourceful", "You're versatile", "You're flexible", "You're adaptable", 
    "You're agile", "You're nimble", "You're quick-witted", "You're sharp-minded", 
    "You're clear-headed", "You're focused", "You're alert", "You're attentive", 
    "You're observant", "You're perceptive", "You're insightful", 
    "You're thoughtful", "You're considerate", "You're compassionate", 
    "You're empathetic", "You're kind", "You're generous", "You're giving", 
    "You're caring", "You're loving", "You're affectionate", "You're warm", 
    "You're friendly", "You're sociable", "You're outgoing", "You're gregarious", 
    "You're talkative", "You're articulate", "You're expressive", 
    "You're communicative", "You're understanding", "You're patient", 
    "You're tolerant", "You're forgiving", "You're open-minded", 
    "You're fair-minded", "You're just", "You're impartial", "You're unbiased", 
    "You're objective", "You're neutral", "You're balanced", "You're reasonable", 
    "You're rational", "You're logical", "You're sensible", "You're practical", 
    "You're down-to-earth", "You're realistic", "You're pragmatic", 
    "You're level-headed", "You're calm", "You're composed", "You're serene", 
    "You're peaceful", "You're content", "You're satisfied", "You're fulfilled", 
    "You're happy", "You're joyful", "You're cheerful", "You're jolly", 
    "You're merry", "You're lively", "You're enthusiastic", "You're energetic", 
    "You're vibrant", "You're dynamic", "You're spirited", "You're passionate", 
    "You're zealous", "You're motivated", "You're driven", "You're ambitious", 
    "You're eager", "You're excited", "You're enthusiastic", "You're optimistic", 
    "You're hopeful", "You're positive", "You're confident", "You're assertive", 
    "You're strong", "You're resilient", "You're tough", "You're brave", 
    "You're courageous", "You're bold", "You're fearless", "You're daring", 
    "You're adventurous", "You're curious", "You're inquisitive", "You're inventive", 
    "You're innovative", "You're creative", "You're imaginative", "You're original", 
    "You're resourceful", "You're versatile", "You're flexible", "You're adaptable", 
    "You're agile", "You're nimble", "You're quick-witted", "You're sharp-minded", 
    "You're clear-headed", "You're focused", "You're alert", "You're attentive", 
    "You're observant", "You're perceptive", "You're insightful", 
    "You're thoughtful", "You're considerate", "You're compassionate", 
    "You're empathetic", "You're kind", "You're generous", "You're giving", 
    "You're caring", "You're loving", "You're affectionate", "You're warm", 
    "You're friendly", "You're sociable", "You're outgoing", "You're gregarious", 
    "You're talkative", "You're articulate", "You're expressive", 
    "You're communicative", "You're understanding", "You're patient", 
    "You're tolerant", "You're forgiving", "You're open-minded", 
    "You're fair-minded", "You're just", "You're impartial", "You're unbiased", 
    "You're objective", "You're neutral", "You're balanced", "You're reasonable", 
    "You're rational", "You're logical", "You're sensible", "You're practical", 
    "You're down-to-earth", "You're realistic", "You're pragmatic", 
    "You're level-headed", "You're calm", "You're composed", "You're serene", 
    "You're peaceful", "You're content", "You're satisfied", "You're fulfilled", 
    "You're happy", "You're joyful", "You're cheerful", "You're jolly", 
    "You're merry", "You're lively", "You're enthusiastic", "You're energetic", 
    "You're vibrant", "You're dynamic", "You're spirited", "You're passionate", 
    "You're zealous", "You're motivated", "You're driven", "You're ambitious", 
    "You're eager", "You're excited", "You're enthusiastic", "You're optimistic", 
    "You're hopeful", "You're positive", "You're confident", "You're assertive", 
    "You're strong", "You're resilient", "You're tough", "You're brave", 
    "You're courageous", "You're bold", "You're fearless", "You're daring", 
    "You're adventurous", "You're curious", "You're inquisitive", "You're inventive", 
    "You're innovative", "You're creative", "You're imaginative", "You're original", 
    "You're resourceful", "You're versatile", "You're flexible", "You're adaptable", 
    "You're agile", "You're nimble", "You're quick-witted", "You're sharp-minded", 
    "You're clear-headed", "You're focused", "You're alert", "You're attentive", 
    "You're observant", "You're perceptive", "You're insightful", 
    "You're thoughtful", "You're considerate", "You're compassionate", 
    "You're empathetic", "You're kind", "You're generous", "You're giving", 
    "You're caring", "You're loving", "You're affectionate", "You're warm", 
    "You're friendly", "You're sociable", "You're outgoing", "You're gregarious", 
    "You're talkative", "You're articulate", "You're expressive", 
    "You're communicative", "You're understanding", "You're patient", 
    "You're tolerant", "You're forgiving", "You're open-minded", 
    "You're fair-minded", "You're just", "You're impartial", "You're unbiased", 
    "You're objective", "You're neutral", "You're balanced", "You're reasonable", 
    "You're rational", "You're logical", "You're sensible", "You're practical", 
    "You're down-to-earth", "You're realistic", "You're pragmatic", 
    "You're level-headed", "You're calm"
];



let sendMsgButton = document.getElementById("sendMsgButton");
let userInputEl = document.getElementById("userInput");
let chatContainerEl = document.getElementById("chatContainer");

sendMsgButton.onclick = function()
{
    let userInputVal = userInputEl.value;

    let msgToChatbotContainer = document.createElement("div");
    msgToChatbotContainer.classList.add("msg-to-chatbot-container");
    chatContainerEl.appendChild(msgToChatbotContainer);

    let msgToChatbot = document.createElement("span");
    msgToChatbot.classList.add("msg-to-chatbot");
    msgToChatbot.textContent = userInputVal;
    msgToChatbotContainer.appendChild(msgToChatbot);

    chatBotReply();
    userInputEl.value = "";
}

function chatBotReply()
{
    let noOfBotMsgs = chatBotMsgList.length;
    let botMsg = chatBotMsgList[Math.ceil(Math.random() * noOfBotMsgs) - 1]

    let msgFromChatbotContainer = document.createElement("div");
    msgFromChatbotContainer.classList.add("msg-from-chatbot-container");
    chatContainerEl.appendChild(msgFromChatbotContainer);

    let msgFromChatbot = document.createElement("span");
    msgFromChatbot.classList.add("msg-from-chatbot");
    msgFromChatbot.textContent = botMsg;
    msgFromChatbotContainer.appendChild(msgFromChatbot);
}